ITEM:
  material: BEACON
  damage: 0
  amount: 1
  name: "&8» &c&lChunk Buster &8«"
  lore:
    - ""
    - "&fPlace me to mine out"
    - "&fan entire Chunk from"
    - "&fSky limit to Bedrock."
    - ""
    - "&c&lNOTE"
    - "&7You may only place &f1"
    - "&7Chunk buster every &f10 &7seconds."
    - ""
SETTINGS:
  MAX_MILLIS_PER_TICK: 0.5 # RECOMMENDED: 0.5 (SLOWER AND PERFORMANCE FRIENDLY), ULTRA FAST: 15 (ULTRA FAST AND PERFORMANCE FRIENDLY)
  APPLY_PHYSICS: false
  SINGLE_WORK_LOAD: false #This option is not available at the moment.
  MIN_HEIGHT: -63 # PUT AT 0 IF YOU ARE ON 1.8 (to get better performances)!
  MAX_HEIGHT: 320 # PUT THE VALUE THAT YOU'VE PUT IN THE SPIGOT CONFIGS
  COOLDOWN: 10 #Cooldown time in seconds (0 or -1 to disable)
  DELAY_BEFORE_START: 5 #Delay in seconds (0 to disable)
  MESSAGES:
    FINISH: "&c&lChunkBuster &8➼ &7Your ChunkBuster at (%x%, %z%) has been finished. (%time% seconds, %totalBlocks% blocks)"
    START: "&c&lChunkBuster &8➼ &7Your ChunkBuster task is now starting. You have &c5 &7seconds to find a safe location."
    COOLDOWN: "&c&lChunkBuster &8➼ &cYou cannot place another ChunkBuster for %cooldown% second%context%." #Context adds 's' if seconds equals to 0 or higher than 1