name: ChunkBuster
version: '${project.version}'
main: me.overkidding.chunkbuster.ChunkBuster
api-version: 1.13
authors: [ overkidding ]
description: Destroys the chunk the player is standing on.
commands:
  chunkbuster:
    description: Main command